//==============================================================================
// Module      : demo_top
// Description : Self-contained synthesizable DEMO TOP that exercises the FIFO
//               suite end-to-end and routes to a real FPGA bitstream. A free-
//               running counter streams data through an AXI4-Stream width
//               converter chain (8b -> 32b up-size, then 32b -> 8b down-size,
//               back to the original width) and a self-checker compares the
//               round-tripped byte against a reference model. Any mismatch
//               latches an error; the single status output `led` blinks while
//               data keeps matching and goes solid-off on a (never-expected)
//               error, so the design has observable behaviour on a board with
//               just a clock, a reset button, and one LED.
// Parameters  : (none — fixed geometry so the bitstream is deterministic)
// Author      : William Mar
// Date        : 2026-06
// Notes       : Pure synthesizable logic — no testbench constructs. Routes on
//               both Lattice targets via scripts/build_bitstream.sh
//               (yosys -> nextpnr -> ecppack/icepack). The point is to prove the
//               RTL goes through a real place-and-route + bitstream-pack flow,
//               not to validate function (that is the formal + Verilator job).
//
// Datapath:  cnt(8b) --s_axis--> [axis_width_conv 8->32] --> [axis_width_conv
//            32->8] --m_axis--> checker vs delayed reference --> err latch -> led
//==============================================================================

`default_nettype none

module demo_top (
    input  wire clk,
    input  wire rst_n,     // active-low reset (board button)
    output wire led        // heartbeat while data matches; off on error
);

    localparam int W   = 8;
    localparam int WUP = 32;

    // ------------------------------------------------------------------
    // Stimulus: a free-running byte counter, offered continuously.
    // ------------------------------------------------------------------
    logic [W-1:0] gen_data;
    always_ff @(posedge clk) begin
        if (!rst_n) gen_data <= '0;
        else if (s0_tready) gen_data <= gen_data + 1'b1;
    end
    wire           s0_tvalid = 1'b1;        // always offering
    wire           s0_tready;

    // ------------------------------------------------------------------
    // Stage 0: up-size 8b -> 32b.
    // ------------------------------------------------------------------
    wire           up_tvalid;
    wire           up_tready;
    wire [WUP-1:0] up_tdata;

    axis_width_conv #(
        .S_WIDTH (W), .M_WIDTH (WUP), .DEPTH_NARROW (16)
    ) u_up (
        .clk (clk), .rst_n (rst_n),
        .s_axis_tvalid (s0_tvalid), .s_axis_tready (s0_tready), .s_axis_tdata (gen_data),
        .m_axis_tvalid (up_tvalid), .m_axis_tready (up_tready), .m_axis_tdata (up_tdata)
    );

    // ------------------------------------------------------------------
    // Stage 1: down-size 32b -> 8b (recovers the original byte stream).
    // ------------------------------------------------------------------
    wire         dn_tvalid;
    wire         dn_tready;
    wire [W-1:0] dn_tdata;

    axis_width_conv #(
        .S_WIDTH (WUP), .M_WIDTH (W), .DEPTH_NARROW (16)
    ) u_dn (
        .clk (clk), .rst_n (rst_n),
        .s_axis_tvalid (up_tvalid), .s_axis_tready (up_tready), .s_axis_tdata (up_tdata),
        .m_axis_tvalid (dn_tvalid), .m_axis_tready (dn_tready), .m_axis_tdata (dn_tdata)
    );

    // Always accept the final output.
    assign dn_tready = 1'b1;

    // ------------------------------------------------------------------
    // Self-checker: the Nth delivered byte must equal the Nth generated byte.
    // A reference counter advances on each accepted master beat; mismatch
    // latches err. (Little sub-word order is identity, so the round-trip
    // up->down reproduces the original byte sequence exactly.)
    // ------------------------------------------------------------------
    logic [W-1:0] ref_data;
    logic         err;
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            ref_data <= '0;
            err      <= 1'b0;
        end else if (dn_tvalid && dn_tready) begin
            if (dn_tdata != ref_data) err <= 1'b1;
            ref_data <= ref_data + 1'b1;
        end
    end

    // ------------------------------------------------------------------
    // Heartbeat: a slow blink so a board shows liveness; forced off on error.
    // ------------------------------------------------------------------
    logic [23:0] beat;
    always_ff @(posedge clk) begin
        if (!rst_n) beat <= '0;
        else        beat <= beat + 1'b1;
    end
    assign led = err ? 1'b0 : beat[23];

endmodule

`default_nettype wire
